### ISSUE TITLE
[knb] - init is not working

### ISSUE THREAD

**Issue by porres** [Ant1r/pure-data#10]
saving a patch with a knob value and "init" doesn't work. When you load the patch, is like it had no "init"

**Comment by Ant1r** [comment]
I cannot reproduce. It seems to me that "init" works as expected.
Can you share a patch?

**Comment by umlaeute** [comment]
works for me as well.

**Comment by porres** [comment]
have you tried connecting to a number box to see if the value comes out?

Here's a patch, see how the slider does that, but knob doesn't
 
[knb-init.pd.zip](https://github.com/Ant1r/pure-data/files/4426843/knb-init.pd.zip)

**Comment by Ant1r** [comment]
weird, it's working for me:
![Capture du 2020-04-03 13-52-23](https://user-images.githubusercontent.com/3748246/78357835-6ce81900-75b2-11ea-9301-4dbf2b6c0104.png)

**Comment by porres** [comment]
weird as hell...

<img width="322" alt="Screen Shot 2020-04-03 at 08 55 46" src="https://user-images.githubusercontent.com/5360142/78358068-ef5be300-7588-11ea-8ea6-4317faed1457.png">

**Comment by porres** [comment]
i'm on macOS of course... hmm

**Comment by Ant1r** [comment]
OK! I think I nailed it:
89ace76f6c23929853661c0cfee68ea80cbf74c6

loadbang method wasn't declared accepting a "float" as argument...

**Comment by porres** [comment]
works now!
