### ISSUE TITLE
[knb] documentation and outline + iolet hiding

### ISSUE THREAD

**Issue by porres** [Ant1r/pure-data#11]
help file says

"note: when selected, knb shows its inlet, outlet and a rectangular outline, in order to help connecting. When edit mode is switched off, they disapear after the mkob is hovered by the mouse or the knob value is changed."

This is different now, first because by default, it will show the outlet + iolet. Moreover, if you have s/r names, they won't show up at all ever...

And although you still have this behaviour that it will show the outline when you select it in edit mode, I think we don't need this anymore, so we'd need to remove this from the code.

All we need to do is document that when we hide io;et with s/r names, outline is also hidden.

**Comment by Ant1r** [comment]
> I think we don't need this anymore

well, I find it really useful to have the outlines in edition mode, because it helps a lot for positioning precisely outline-less knobs. That's why I'm reluctant to remove it...

**Comment by porres** [comment]
i'm not sure what you mean, can you give me an example?

**Comment by Ant1r** [comment]
![Capture du 2020-04-03 14-36-59](https://user-images.githubusercontent.com/3748246/78361373-9a37c580-75b8-11ea-96b6-487eb0efc97c.png)

it seemed to me that it would be harder to place the knobs like this without the square outlines.
But I may be wrong actually...

That said I just noticed a bug about this point: if I minimize the patch window, then when I display it again, the outlines and iolets of not-s/r-defined knobs are not shown anymore!

**Comment by porres** [comment]
> I just noticed a bug about this point: if I minimize the patch window, then when I display it again, the outlines and iolets of not-s/r-defined knobs are not shown anymore!

confirmed...

> it seemed to me that it would be harder to place the knobs like this without the square outlines. But I may be wrong actually...

yeah, honestly, I don't see how that's so. But then, what I really do to align objects like this is a simple "Tidy Up" (select a few objects in a row and hit "shift + command/control + R", voilà!

Duplicating an object and then using shift + left-arrow also helps getting the object in the same alignment.

And you can see the objects touching each other regardless of the outlines

**Comment by porres** [comment]
Anyway, I really don't think drawing outline is necessary while in edit mode, but my main issue with it is that the process is not simple. It should really just react by getting in and out of edit mode.

I know there was a discussion about it and I finally read the link you sent me before: https://lists.puredata.info/pipermail/pd-list/2018-09/123354.html

And, like I had said, I was doing something like that for my externals, and I was actually doing what Katja proposed (some hacky thing based on messages sent to the canvas - like using iemguts/receivecanvas).

Now, if this was an external, you could try and do that as well. But note that now that we're having this as an internal, maybe there can be a simpler way. I mean, in the same way that comments do. I'm just assuming that being knob an internal, we could do it.

I'm also inquiring the pd-dev list how to make this simpler for externals...

Anyway, having said all that, I'd still like to emphasize how I don't think it's necessary :)

**Comment by Ant1r** [comment]
>  I'd like to emphasize

yes I had already noticed ;-)

OK OK! I've removed it, see 9f9fa9feada198581391bb34a52c78bf44991b2f
And I fixed the "minimize" bug BTW.

**Comment by porres** [comment]
Awesome, I'm closing this then, and see https://github.com/Ant1r/pure-data/pull/12 for an update of the help file
