### ISSUE TITLE
[knb] 4th color for Arc

### ISSUE THREAD

**Issue by Ant1r** [Ant1r/pure-data#13]
Wouldn't it be forth it to add a 4th color for drawing the arc?
So we could draw smth like:
![Capture du 2020-04-04 15-10-03](https://user-images.githubusercontent.com/3748246/78451625-e5b8a500-7686-11ea-8be5-641890104ba4.png)
It seems to me that it wouldn't involve a lot of work.

**Comment by Ant1r** [comment]
Ping @porres @umlaute @megrimm

**Comment by porres** [comment]
it could be useful, but I'm ok with just 3 colors like other iemguis

**Comment by Ant1r** [comment]
I meant @umlaeute ...

**Comment by porres** [comment]
> it could be useful, but I'm ok with just 3 colors like other iemguis

you know I'm an advocate for simplicity, I'm more concerned about taking one or two things off as it is, not add more ;) I wouldn't really mind too much this option, and that is to say I have other things I mind more and wish could be simplified, specially if we're adding more stuff like this.

**Comment by megrimm** [comment]
yeah i would agree. i don't mind the extra color too much BUT if we want consistency with other  gui objects then maybe not....???

if we were to take something out the triangle could come out and we just have a line. I think the line is enough and looks good too.

**Comment by umlaeute** [comment]
i agree that i probably would never use the triangle and only ever the line-wiper.

from an API-pov i would recommend to still use the symbolic names (e.g. `line` vs `none`) for the wpier-styles.

regarding the 4th colour: i don't really care either.

**Comment by porres** [comment]
I have an idea!

As for consistency, truth be told, [cnv] has no front color, and that's fine cause it can't. So it's not a rule, and maybe now we have a GUI that can have 4 colors, why not? So, a consistency rule is not a good argument.

Now, being able to set independently the color of the line and the arc, one can set the color of the line the same as the background, emulating a "none" setting.

Now, if most of us agree just a line is fine, we can think about only have a single line setting and no parameter to change for "none" and "line"!

**Comment by Ant1r** [comment]
Ok I'll remove the triangle. 
If I add an "arc_color", then the "wiper_style" setting  could be removed as well. The wiper could be hidden if fg_color==bg_color .

**Comment by porres** [comment]
yup, that's my thought, and I guess we can also check later what's the best way to deal with this.

I'm thinking that the arc is always drawn on top of the line and that maybe it should always be drawn for the start value (or "0" value for +/- knob). This is because I already mentioned how I thought it was weird to not have a clear visual cue where the start point of the knob is when we have a "no line" setting.

I guess this is more of a parallel issue, but what do you think?

**Comment by umlaeute** [comment]
i'd actually would like a *transparent* setting much more (i know that the other iemguis don't really allow  for no-color; but still...)

**Comment by porres** [comment]
> i know that the other iemguis don't really allow for no-color; but still...

well, that's an idea to implement this for all of them for consistency

An alpha parameter would also be great so you could control the transparency!

**Comment by Ant1r** [comment]
Alpha is not an option with TclTk I'm afraid...

But no color would be cool indeed! And certainly other widgets should support it too. I'll have a look to know how it could be done.

**Comment by porres** [comment]
> But no color would be cool indeed! And certainly other widgets should support it too. I'll have a look to know how it could be done.

Seems we could bother with this later, cause it involves other objects for consistency. I opened a request for it so we don't forget about it -> https://github.com/pure-data/pure-data/issues/925

**Comment by porres** [comment]
I see you've added it and it looks great!

we can close this now ;)

**Comment by porres** [comment]
@Ant1r 

> Alpha is not an option with TclTk I'm afraid...

I see there's at least this https://www.tcl.tk/man/tcl8.4/TkCmd/wm.htm#M12

but this is just for a window, like a patch canvas, huh? Weird... how come there's not this for a widget?

**Comment by umlaeute** [comment]
>
>but this is just for a window, like a patch canvas, huh? Weird... how
>come there's not this for a widget?

you probably should ask this on the tcl/tk tracker.
for our purpose i think it's enough to know that there's no alpha channel (and my original request was about "no color" rather than "colors with transpatency)
