### ISSUE TITLE
[knb] - arc doesn't fit well in the knob circle on macOS

### ISSUE THREAD

**Issue by porres** [Ant1r/pure-data#2]
this is easier to spot in smaller knob sizes, see picture

<img width="170" alt="78042964-23e15c00-7349-11ea-97dd-029ad8eacdef" src="https://user-images.githubusercontent.com/5360142/78164431-1e0a7a00-7420-11ea-907e-7f4b7c21dbf3.png">

**Comment by Ant1r** [comment]
as a recall it doesn't appear on my Linux machine:
![Capture du 2020-04-01 11-55-22](https://user-images.githubusercontent.com/3748246/78164815-a9990080-744a-11ea-8d7b-8bf2ca29ed14.png)

**Comment by umlaeute** [comment]
@porres could you provide a patch (or an invocation of the [knb] object) that exhibits the problem?

**Comment by porres** [comment]
Any knob with style "wiper+arc" shows this for me, here's a patch with 3 different sizes

[test.pd.zip](https://github.com/Ant1r/pure-data/files/4417436/test.pd.zip)

now, I couldn't get "init" to work on knob, so I'm using loadbang (will open a new issue for it.

Anyway, funny enough, I don't see the same issue when zooming in! But I do see that the circle does not fully close (more apparent in bigger sizes).

Screenshots:

**No zoom:**
<img width="252" alt="Screen Shot 2020-04-01 at 17 25 30" src="https://user-images.githubusercontent.com/5360142/78183395-37222380-743e-11ea-9d67-99a18cfa5e02.png">

**Zoomed:**
<img width="457" alt="Screen Shot 2020-04-01 at 17 25 41" src="https://user-images.githubusercontent.com/5360142/78183428-45703f80-743e-11ea-8040-2bd2033918e2.png">

**Comment by porres** [comment]
Actually, when zoomed, we also have an issue with the arc not really fitting the circle, it has a minor offset

**Comment by porres** [comment]
> Anyway, funny enough, I don't see the same issue when zooming in! But I do see that the circle does not fully close (more apparent in bigger sizes).

I can actually see that too when zoomed out, but it's just way smaller so it's harder to notice

**Comment by porres** [comment]
now that we can set the arc size, I can see that when you are zoomed out, the arc line will in fact fit in the circle if we have an odd number of pixel width! Maybe this is an important cue... 

so then it only gets a little offset if you have an even number for the pixel sizes

As for negative values, a similar thing happens. You can see an offset change if you switch from an even/odd size. An odd number seems to be better centered into the circle without offsets, but it does generate an "empty spot" right in the middle of the circle.

A related issue is this https://github.com/Ant1r/pure-data/issues/5 where a size of zero draws a point in the middle of the circle

**Comment by Ant1r** [comment]
this is probably the biggest problem here...

It could be related to the way Tk behaves with Retina sub-pixel interpolation. Since Tk only support integer coordinates, the behavior with sub-pixel screen may be not clearly defined.

Moreover this could also be related to drawing arc with significant linewidth, which is somewhat different of drawing circles and filled arcs.

If it turns out that this relates to actual differentiated drawing of thick arcs across OSes, maybe we'll have to get rid of so-called thick arcs... 

In this case, I have an idea: we could get rid of "arc width" parameter, make the arc an actual filled arc (so it would always draw like the current `arc_width = size/2` case), and add an `arc_color` parameter instead. Should I code a proposal along these lines?

**Comment by porres** [comment]
it is not related to thick arcs. Like I said, if the arc size is an odd number, things are fine. Maybe a quick hacky solution for now is to allow only odd values for the "arc" messages (1, 3, 5, 7, 9, 11). I mean, it should allow even numbers, but values would get rounded to odd values.

**Comment by Ant1r** [comment]
OK, I could do that.

**Comment by Ant1r** [comment]
@porres would you try the latest fix cc45ff56130b09917a40d79bc01a31a2d194571d please?

**Comment by porres** [comment]
I tried and it still behaves funny, but I see it still allows odd and even numbers

**Comment by Ant1r** [comment]
yes, I wanted to see if we could fix that without disallowing even numbers... which I'd prefer to avoid.

**Comment by Ant1r** [comment]
Could you please send a snapshot with a 
`size=100 arc=1 wiper=none angle=(-180;180) value=max` 
knob please?
e.g I have this:
![Capture du 2020-04-04 15-55-07](https://user-images.githubusercontent.com/3748246/78452662-c6bd1180-768c-11ea-9039-74b621157ba8.png)

**Comment by Ant1r** [comment]
sorry, can you also post the same with `width=101` ?
for me it's like this:
![Capture du 2020-04-04 16-02-07](https://user-images.githubusercontent.com/3748246/78452785-a5105a00-768d-11ea-81f1-369f36badbd1.png)

**Comment by porres** [comment]
I dont get, for an arc of one, this is what I have
<img width="171" alt="Screen Shot 2020-04-04 at 11 02 48" src="https://user-images.githubusercontent.com/5360142/78452802-dc6a1100-7663-11ea-9338-97a368c02504.png">

**Comment by porres** [comment]
size of 100, maximum arc size is 49, this is what I get 

<img width="150" alt="Screen Shot 2020-04-04 at 11 07 20" src="https://user-images.githubusercontent.com/5360142/78452886-86499d80-7664-11ea-98f8-450ce4d564c4.png">

**Comment by porres** [comment]
size of 101, maximum arc size is 50, this is what I get

<img width="213" alt="Screen Shot 2020-04-04 at 11 09 10" src="https://user-images.githubusercontent.com/5360142/78452922-c3159480-7664-11ea-8b1c-1237801e28ac.png">

same size of 101 but an arc of 49 makes it look well centered again and fits fine!

<img width="142" alt="Screen Shot 2020-04-04 at 11 09 47" src="https://user-images.githubusercontent.com/5360142/78452940-e3455380-7664-11ea-8064-ea31c484226d.png">

**Comment by porres** [comment]
also with wiper none, this is something I get. When it is fully off, I still can see a thin gray line, check below on the left. And when it is fully on, as in the right, you can see there's a hole in the middle point and a thin while unfilled line.

<img width="306" alt="Screen Shot 2020-04-04 at 11 11 15" src="https://user-images.githubusercontent.com/5360142/78452976-2bfd0c80-7665-11ea-9ece-2ffd7f0c30ef.png">

**Comment by Ant1r** [comment]
Thanks, but I'd be interested by a minimal arc_width. So you don't see the the arc if `arc_width=1`? Interesting... Can you try with a non-black arc color? And also try with `arc_width=2` if nothing is visible. Always keep `size=101`.

**Comment by Ant1r** [comment]
(and sorry I should have told you: on my latest screenshots the setting was bg_color=black fg_color=white)

**Comment by porres** [comment]
here you go

<img width="339" alt="Screen Shot 2020-04-04 at 11 39 21" src="https://user-images.githubusercontent.com/5360142/78453566-fa864000-7668-11ea-8d63-3d10dea6b842.png">

**Comment by Ant1r** [comment]
great, so with `width=1` centering is good.

Is it still the case with `width=2` `width=3` etc? Is the centering bad above a certain arc width value, or is this related only to arc width being odd? 

In the latter case only arc width would have to be restricted to odd numbers, which I would find much better than restricting size.

Please do test, and if you have some findings, try the same with even knob size setting.

**Comment by porres** [comment]
> Is it still the case with width=2 width=3 etc? Is the centering bad above a certain arc width value, or is this related only to arc width being odd?

it's related only to arc width being odd

**Comment by porres** [comment]
actually, being even... odd is how it looks nice!

**Comment by Ant1r** [comment]
so does every setting draw fine on MacOS now? Can we close this issue?

**Comment by porres** [comment]
Oh, I see you already have implemented a rounding thing

well, it's almost perfect

The only thing is that if we have an even size, like '50', then the biggest arc size is clipped at 24!

it Doesn't allow me to set 25, and I think it should do that

Cause if I set it to 23, I still see an empty spot in the middle

**Comment by porres** [comment]
> if we have an even size, like '50', then the biggest arc size is clipped at 24!

apparently, if you set the arc size as a message, it doesn't get clipped, so it can go higher, but then, it should really get clipped to half its size + 1. 

As for something like 49, it also gets clipped at 24, so it should also go up to 25

**Comment by porres** [comment]
> if we have an even size, like '50', then the biggest arc size is clipped at 24!

apparently, if you set the arc size as a message, it doesn't get clipped, so it can go higher, but then, it should really get clipped to half its size. 

As for something like 49, it also gets clipped at 24, so it should also go up to 25 - so it should get clipped to half its size and rounded up to ceil (25).

**Comment by Ant1r** [comment]
Hell, once again our results differ! 

On my display things are OK now; if I increase the maximum arc width I end up with a little glitch sticking out at the center.

I'm sure what to do; I'd prefer to avoid introducing OS specific code...

BTW you're right, arc message should also clip. Either way, note that it's done before drawing (by `knb_update_knob(`) function)

**Comment by Ant1r** [comment]
OK I've rewritten the way the arc is drawn (https://github.com/Ant1r/pure-data/commit/5703bff156a696661cd4551cf6d3d4e6afb62195).
BTW I've removed the even-number forcing for arc width, in the hope it's no longer needed.

@porres would you mind trying on Macos?
@spacechild1 would it be possible for you to try on Windows (https://github.com/pure-data/pure-data/pull/919)?

What it should do (i.e what to test, whatever the knob size):
- everything should always be concentric
- if `arc_width = 1` then the 1-pixel-wide touches the overall circle outline (and so on for any positive value)
- if `arc_width = (size - 1) / 2` (e.g `size = 40, arc = 19`) then the arc is full (up to the center)
- if `arc_width = -1 *((size - 1) / 2 + 1)` (e.g `size = 40, arc = -20`) then the arc overwrites the circle outline

many thanks!

**Comment by porres** [comment]
it's working perfectly

**Comment by umlaeute** [comment]
so this issue can be closed?
