### ISSUE TITLE
[knb] user-configurable arc-styles instead of presets

### ISSUE THREAD

**Issue by umlaeute** [Ant1r/pure-data#4]
> ### styles

> Arc : none / thin / bold / half / full

how about allowing the user to specify the thickness rather than providing presets?

| value | effect | example |
| --- | --- | --- |
| 0 | no arc | ![none](https://user-images.githubusercontent.com/214034/78112406-77fa4800-73fe-11ea-81a8-67a1d96ba279.png)
| 1 | thin arc ("1 pixel") | ![thin](https://user-images.githubusercontent.com/214034/78112425-7e88bf80-73fe-11ea-988e-e758e9fb293c.png)
| 5 | thicker arc ("5 pixels") | ![thick](https://user-images.githubusercontent.com/214034/78112469-8f393580-73fe-11ea-97ab-d5bfd3253c08.png)
| <size/2> | full arc | ![full](https://user-images.githubusercontent.com/214034/78112620-c60f4b80-73fe-11ea-966b-c94c2666ec34.png)
| -5 | thick  ("5 pixels") inverted arc | ![inverted](https://user-images.githubusercontent.com/214034/78112641-cc9dc300-73fe-11ea-9591-a12a17f9d75f.png)

**Comment by Ant1r** [comment]
I like it. Should the thickness be in %  of the radius, or is pixel better?

**Comment by umlaeute** [comment]
i don't really know. it's easy enough to convert between the two on the patch-level.

i don't think (but might miss the obvious) that any of the iemguis use a relative size anywhere, so that would favour absolute pixels.

**Comment by umlaeute** [comment]
but if you go for relative, probably just use normalized values (-1..+1) rather than percent.

**Comment by Ant1r** [comment]
let's go pixels

**Comment by umlaeute** [comment]
i guess this is now implemented(as of 706bf650e994126def10e1e76ddaa77cc2921310)
