### ISSUE TITLE
[knb] - wiper none and arc width of 0 draws a dot

### ISSUE THREAD

**Issue by porres** [Ant1r/pure-data#5]
If I have "wiper none" and and arc width of 0, [knb] draws a dot in the center of the circle.

I don't think it should draw anything for a zero setting. This mid point dot seems to be what we should get for a setting of -1

**Comment by Ant1r** [comment]
mmm.. I cannot reproduce here!
Yet another Tk bug I guess...

**Comment by Ant1r** [comment]
Well @porres are you sure this is not related to #9?
I mean can you see the center-dot even after you configured the knob through its properties dialog?

**Comment by porres** [comment]
I tried now compiled with the last commit, and this doesn't happen no more... so I'm closing it.

> Well @porres are you sure this is not related to #9?

not really, as that one persists
