### ISSUE TITLE
[knb] - fix compilation warnings

### ISSUE THREAD

**Issue by porres** [Ant1r/pure-data#6]
I see many compilation warnings that could be removed by cleaning up the code and avoiding issues.

For instance: **use "fabs" instead of "abs".**

Remove unused variables:

g_knb.c:195:9: warning: unused variable 'r' [-Wunused-variable]
    int r = xpos + (x->x_val + 50) / 100;
        ^
g_knb.c:381:9: warning: unused variable 'bflcol_compat' [-Wunused-variable]
    int bflcol_compat[3];
        ^
g_knb.c:417:9: warning: unused variable 'H' [-Wunused-variable]
    int H;
        ^
g_knb.c:430:9: warning: unused variable 'H' [-Wunused-variable]
    int H;

anyway, check them out...

**Comment by umlaeute** [comment]
but only after the code is polished enough to be accepted.

**Comment by porres** [comment]
what do you mean? Cause by then there may be more new warnings?

**Comment by umlaeute** [comment]
it's just pointless to spend time on that right now.

**Comment by Ant1r** [comment]
Anyway It was quickly fixed with 4ee16331716720b49a420fce8a55a12db24ab578
