### ISSUE TITLE
[knb] remove lin/log scale

### ISSUE THREAD

**Issue by umlaeute** [Ant1r/pure-data#8]
it seems that [knb] has inherited the lin/log scale toggle from the sliders.

i don't see much point in heaving a non-linear scale for a rotary controller, so i suggest to remove them.
(it's easy enough to put a `[dbtorms]` after the knob if you want to use it to control loudness)

**Comment by porres** [comment]
> i don't see much point in heaving a non-linear scale for a rotary controller,

why not? 

By the way, I don't like the log scaling of iemguis at all, they seem quite arbitrary and I don't get where they come from. And note they are not only for sliders, but number box has it too!

If it was just for sliders and not the number box, then I guess it'd be fine to not have it in knob. But removing it from knob would make this one the odd one out.

Again, not that I like the log scale of iemguis or find it useful for anything.

**Comment by Ant1r** [comment]
I'm thinking pretty much like Alex.
I rarely (although it can happen) use the Log scale. 
But it doesn't seem consistent to me not to have this feature for knobs.

That said, if there is a consensus on that, I'll happily remove it!

**Comment by umlaeute** [comment]
well whatever.
i find it a bit confusing to have both `lin` and `Linear control` in the settings.
and then there's also `line` (wiper style) and `Init` (which is a completely different word but looks similar enough).

regarding the general usefulness of the log scale: i personally agree that the sliders could well live without them. not so much the number-boxes (at least if you ever want to use if for frequencies; which we do quite a lot here at uni :-); so that's "where they come from" (building technical interfaces for DSP))

i don't understand that "arbitrary" remark: you can adjust the start/endpoints to your needs.

**Comment by Ant1r** [comment]
would you think of a better wording for `Linear control`?

**Comment by porres** [comment]
> i don't understand that "arbitrary" remark

there's a particular log formula that I don't know where it came from, and the curve seems to depend on the ratio of start/end values if I recall correctly.

A more useful formula, for me, would allow the user to set the steepness of the log curve regardless of start/end values. And it'd be great also if it would allow 0 or negative values.

**Comment by Ant1r** [comment]
It's not arbitrary I think, it's something like:
`exp(pos.log(max/min) + log(min))` (where `pos` is normalized to [0;1])
which seems logical to me.

**Comment by umlaeute** [comment]
> And it'd be great also if it would allow 0 or negative values.

you have to talk with the mathematicians about that.

**Comment by porres** [comment]
haha, I know what you mean, but isn't like just using something like [pow 4] a form of log scale?

**Comment by Ant1r** [comment]
Well [pow 4] doesn't allow negative output either ;-)

**Comment by porres** [comment]
I guess we can close this and just leave the log setting, right?

and anyway, I do have a log scaling in my [else/rescale] object. It's basically [pow] and you can also use negative values, the thing is that the whole range is normalized to 0-1 then rescaled to the output.

I mean, there are ways of handling these things I guess... and what I like about this method is that you can set the steepness of the curve, have 0 and/or negative values, whatever. And that counts as 'log', right?

Another example is how [db2rms] and [rms2db] also have a way to deal with "0"

**Comment by Ant1r** [comment]
Yeah you're right there are many other ways.
Anyway it's still nice that you can just set your pot to [20Hz ; 20kHz]/log and have simple audio freq controller. So I think it's better to keep it for now.
