### ISSUE TITLE
[knb] setting arc-width to >0 after wipe=none doesn't display anything

### ISSUE THREAD

**Issue by umlaeute** [Ant1r/pure-data#9]
at least, if you haven't set any value yet.

1. open the help-patch
   - the rest happens on the right-hand side (message-controlled `[knb]`)
2. click on `[wiper none(`
   - notice that now the `[knb]` doesn't display anything anymore (this is expected)
3. set `[arc 10(`
   - notice that the `[knb]` still doesn't display anything (this is not really expected, but well...)
4. drag the `[knb]`
   -  notice that no values are displayed by the knob (its still functional though, e.. sends data to it's output)

you can get the display back by (temporarily) re-enabling the wiper:

5. click on `[wiper line(`
   - see the current value being displayed by both the arc and the wiper
6. click on `[wiper none(`
   - see the current value being displayed by both the arc only.
     this is what i would have expected right after setting `[arc 10(` above

**Comment by porres** [comment]
when I open the help file of [knb] and use the arc $1 message for the width, the arc doesn't show up. I have to click it on a wiper message to set the style, so maybe this is not only about 
"wiper none"

**Comment by Ant1r** [comment]
fixed.
it was unrelated to "wiper", but only "wiper" message was able to show the arc again. Now the "arc" message works as expected.
